---
# This playbook provisions the website

- name: Provision website
  hosts: arusahni.net
  become: yes
  become_method: sudo
  vars:
    - domain_names:
      - arusahni.net
      - www.arusahni.net
    - server_admin_email: admin@arusahni.net
    - webroot_path: /www/website
  tasks:
    - name: Install necessary packages
      apt: pkg={{ item }}
      with_items:
        - vim
        - nginx
        - htop
    - name: Create web root directory
      file:
        path: "{{ webroot_path }}"
        state: directory
        owner: "{{ ansible_user }}"
      notify: restart nginx
    - name: Configure Nginx
      copy:
        src: website.nginx.conf
        dest: /etc/nginx/sites-available/website
      tags:
        - nginx
      notify: restart nginx
    - name: Disable default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      tags:
        - nginx
      notify: restart nginx
    - name: Enable website
      file:
        src: /etc/nginx/sites-available/website
        dest: /etc/nginx/sites-enabled/website
        state: link
      tags:
        - nginx
      notify: restart nginx
  roles:
    - letsencrypt
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
